### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by drbeat** [strohel/mp3gain#1]
which compiler did you use for compiling?
when i use cygwin64 it doesnt work and with cygwin32 neither

**Comment by strohel** [comment]
Hi, I compile it using gcc on Linux, never tried on Windows, the code might as well need porting effort to work on windows. What is the exact and complete error message?

**Comment by meepzh** [comment]
Just updating that just running `make` worked fine for me, no issues using the software. Using Cygwin 2.5.2 64-bit and gcc 5.4.0. Thanks.
